import json
import numpy as np

from qitker.anyons import logicalQubit
from qitker.parser.sequenceOperation import sequenceOperation
from qitker.QuantumMath.HilbertSpace import hilbertSpace


seqOp = sequenceOperation()

class execution:
    """
    Integration layer between compiler <-> anyons
    
    Attributes:
        - Approximation : np.ndarry
            Matrix the braids create
        - stateVector : np.ndarry
            result of applying on approximation
        - idialMatrix : np.ndarry
            pure gates matrix
        - hilbertOp : hilbertSpace
            mathematical backend    
        - anyonCircuit : list 
            list of logical qubits
        - braidsNumber : int
            number of braids in circuit      
    """


    # initialize execution class
    def __init__(self, circuit):
        
        self.Approximation = np.eye(2, dtype=complex)
        self.stateVector = np.array([1,0], dtype=complex)
        self.idialMatrix = None
        
        self.hilbertOp = hilbertSpace()
        self.anyonCircuit = []
        self.braidsNumber = 0

        qubitsArray = circuit.getQubitsArray()
        for i in qubitsArray: #create the list of qubits
            self.anyonCircuit.append(logicalQubit.logicalQubit())
        
        self.convert(circuit) # Convert high-level quantum gates into low-level braid operations.


  
    def convert(self, circuit):
        """
        Convert quantum operation(gate) to braids 
        Call fidelity function

        Args:
            - circuit (circuit):
                circuit of user

        Returns:
            - None
        """
        
        op = circuit.getOperationVector()
        self.fidelityMatrix(op)
        for i in op:
            self.applyGate(i) #apply each gate appear in operation vector

    
    def fidelityMatrix(self, opType):
        """
        create the idial matrix depends on operations

        Args:
            - circuit (circuit):
                circuit of user

        Returns:
            - None
        """
        
        for num, op in enumerate(opType):
            if num == 0:
                self.idialMatrix = self.hilbertOp.getMatrix(op.getName())
            else:
                self.idialMatrix =  self.hilbertOp.getMatrix(op.getName()) @ self.idialMatrix

            

    def applyGate(self, opType):
        """
        Create new operation sequence and add to the logical qubit
    
        Args:
            - opType (opType):
                operation obj

        Returns:
            - None
        """
        
        name = opType.getName()
        target = opType.getTarget()

        seq = seqOp.getSeq(name)
        self.applySequence(target, seq)
        


            
    def applySequence(self, qubitTarget, seq):
        """
        Apply sequence of sigma(x) on the anyons     
        
        Args:
            - qubitTarget (int):
                id of logical qubit
            - seq (list):
                sigma operation (1, -1, 2, -2, 3, -3...)

        Returns:
            - None
        """
        
        for i in seq:
            self.braidsNumber += 1
            


            self.stateVector = self.anyonCircuit[qubitTarget].sigma(i, self.stateVector, self.hilbertOp)
            self.Approximation = self.hilbertOp.sigma(i, self.Approximation)


            
    def getFidelity(self):
        """
        Return Fidelity (how close our matrix to idial matrix)

        Args:
            - None

        Returns:
            - (float) : fidelity
        """

        return f"{self.hilbertOp.gate_fidelity(self.idialMatrix, self.Approximation)*100:.4f}%"


    def measure(self, shots):
        """
        Measures the quantum state multiple times.

        Args:
            - shots (int): 
                Number of measurement repetitions.

        Returns:
            (dict[int, int]): Measurement counts for each basis state.
        """

        return self.hilbertOp.run_measurements(self.stateVector, shots)
    


    def getMatrix(self):
        """
        Returns the approximated unitary matrix generated by the braid sequence.

        Args:
            None

        Returns:
            (np.ndarray): Approximated unitary matrix.
        """

        return self.Approximation
   

    def getMoveList(self):
        """
        Returns the executed braid operations for each logical qubit.

        Args:
            None

        Returns:
            (list): Report of braid operations grouped by logical qubit.
        """
        
        myList = []
        for i in self.anyonCircuit:
            myList.append(i.getReportList())
        return myList
        
            
    #returning string with basic information on the execution
    def __repr__(self):
        output = ""
        for index, qubit in enumerate(self.anyonCircuit):
            output += f"{index}: {qubit}\n"

        return output